# Generated by Django 5.0.4 on 2024-04-15 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraxialTestData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lvdt', models.JSONField()),
                ('load_100', models.JSONField()),
                ('load_200', models.JSONField()),
                ('strain', models.JSONField()),
                ('corrected_area', models.JSONField()),
                ('deviator_stress_100', models.JSONField()),
                ('deviator_stress_200', models.JSONField()),
            ],
        ),
    ]
