# Generated by Django 5.0.4 on 2024-04-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_strain', '0005_traxialtestdata_degrees_traxialtestdata_radians_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traxialtestdata',
            name='long_text_field',
            field=models.TextField(default=''),
        ),
    ]
